blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Blog(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    date = models.DateField()
    
    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

def all_blogs(request):
    # blogs = Blog.objects.all()
    blogs = Blog.objects.order_by('-date')[:3]
    return render(request, 'blog/all_blogs.html', {'blogs':blogs})

def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog':blog})

portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects':projects})

blog/templates/blog/all_blogs.html
{% extends 'portfolio/base.html' %}
{% load static %}
{% block content %}
<h1>Blog</h1>
<br>
<h2>Frank has written {{ blogs.count }} blog{{ blogs.count|pluralize }}</h2>
<div class="row g-5">
{% for blog in blogs %}
    <a href="{% url 'blog:detail' blog.id %}"><h2>{{ blog.title }}</h2></a>
    <h3>{{ blog.description|safe|truncatechars:100 }}</h3>
    <h3>{{ blog.description|striptags|truncatechars:100 }}</h3>
    <h5>{{ blog.date|date:'M d Y'|upper }}</h5>
    <br>
{% endfor %}
</div>
{% endblock %}

blog/templates/blog/detail.html
{% extends 'portfolio/base.html' %}
{% load static %}
{% block content %}
<div class="row g-5">
  <h1>{{ blog.title }}</h1>
  <h2>-- {{ blog.date|date:'F jS Y' }} --</h2>
  <p>{{ blog.description|safe }}</p>
</div>
{% endblock %}

portfolio/templates/portfolio/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="icon" href="https://franklindecker.com/wp-content/uploads/2022/01/cropped-apple-touch-icon-192x192.png" sizes="192x192" />
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@100&family=Montserrat:wght@500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{ static 'portfolio/custom.css'}" />
    <title>Franklin Decker</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Franklin Decker</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <div class="d-flex ml-auto">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </div>
          <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% static 'portfolio/cv.pdf' %}">CV</a>
            </li>
            <li class="nav-item">
              <a class="btn btn-primary" href="{% url 'blog:all_blogs' %}">Blog</a>
            </li>
          </ul>

        </div>
      </div>
    </nav>

    <main>
      <div class="container">
        {% block content %}{% endblock %}
      </div>
    </main>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}
{% load static %}
{% block content %}
<h1>My Portfolio</h1>

<img src="{% static 'portfolio/porfile-image.png' %}" alt="">

<div class="row g-5">
  {% for project in projects %}
      <h2>{{ project.title }}</h2>
      <h3>{{ project.description }}</h3>
      <img src="{{ project.image.url }}" alt="" width="40">
      {% if project.url %}
      <a href="{{ project.url }}">Link</a>
      {% endif %}
     {% endfor %}
</div>

{% endblock %}